### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "abc",
    "fullname": "Fred",
    "email": "fred@gmail.com",
    "password": "123456"
}

### signup user 2

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "abc",
    "fullname": "Tom",
    "email": "tom@gmail.com",
    "password": "123456"
}


### signin user (valid)

# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json


{
    "email": "fred@gmail.com",
    "password": "123456"
}


### signin user (invalid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "alice@gmail.com",
    "password": "123456"
}

@signin_token = {{signin.response.body.token}}

### create chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{signin_token}}

{
    "name": "abc",
    "members": [1, 2],
    "public": false
}

### get chat list
GET http://localhost:6688/api/chats
Authorization: Bearer {{signin_token}}


### get chat info
GET http://localhost:6688/api/chats/1
Authorization: Bearer {{signin_token}}


### get invalid chat info
GET http://localhost:6688/api/chats/2
Authorization: Bearer {{signin_token}}


### get user list
GET http://localhost:6688/api/users
Authorization: Bearer {{signin_token}}

### upload files
POST http://localhost:6688/api/upload
Authorization: Bearer {{signin_token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="testupload.jpeg"
Content-Type: application/octet-stream

< /home/fredmo/Pictures/testupload.jpeg
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--


### get files
GET http://localhost:6688/api/files/1/eb6/21e/c5a09f99ac4a9a4165e5c26bbf0c052320.jpeg
Authorization: Bearer {{signin_token}}
